// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: src/service/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RAMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // lamport clock timestamp
	Pid       string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`              //process ID
}

func (x *RAMessage) Reset() {
	*x = RAMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_service_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAMessage) ProtoMessage() {}

func (x *RAMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_service_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAMessage.ProtoReflect.Descriptor instead.
func (*RAMessage) Descriptor() ([]byte, []int) {
	return file_src_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *RAMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RAMessage) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type RAReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // lamport clock timestamp
}

func (x *RAReply) Reset() {
	*x = RAReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_service_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAReply) ProtoMessage() {}

func (x *RAReply) ProtoReflect() protoreflect.Message {
	mi := &file_src_service_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAReply.ProtoReflect.Descriptor instead.
func (*RAReply) Descriptor() ([]byte, []int) {
	return file_src_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *RAReply) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_src_service_service_proto protoreflect.FileDescriptor

var file_src_service_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x52, 0x41, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x22, 0x27, 0x0a, 0x07, 0x52, 0x41, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x36, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x12, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x41, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x41, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x6e, 0x64, 0x72, 0x65, 0x61, 0x73, 0x77, 0x61, 0x63, 0x68, 0x73, 0x2f, 0x49, 0x54,
	0x55, 0x2d, 0x44, 0x49, 0x53, 0x59, 0x53, 0x32, 0x30, 0x32, 0x31, 0x2d, 0x45, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x32, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_service_service_proto_rawDescOnce sync.Once
	file_src_service_service_proto_rawDescData = file_src_service_service_proto_rawDesc
)

func file_src_service_service_proto_rawDescGZIP() []byte {
	file_src_service_service_proto_rawDescOnce.Do(func() {
		file_src_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_service_service_proto_rawDescData)
	})
	return file_src_service_service_proto_rawDescData
}

var file_src_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_service_service_proto_goTypes = []interface{}{
	(*RAMessage)(nil), // 0: service.RAMessage
	(*RAReply)(nil),   // 1: service.RAReply
}
var file_src_service_service_proto_depIdxs = []int32{
	0, // 0: service.service.Req:input_type -> service.RAMessage
	1, // 1: service.service.Req:output_type -> service.RAReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_service_service_proto_init() }
func file_src_service_service_proto_init() {
	if File_src_service_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_service_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_service_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_service_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_service_service_proto_goTypes,
		DependencyIndexes: file_src_service_service_proto_depIdxs,
		MessageInfos:      file_src_service_service_proto_msgTypes,
	}.Build()
	File_src_service_service_proto = out.File
	file_src_service_service_proto_rawDesc = nil
	file_src_service_service_proto_goTypes = nil
	file_src_service_service_proto_depIdxs = nil
}
