version: "3.9"
services:
  client1:
    image: disysexercise2
    expose:
    - "5000"
    - "5001"
    - "5002"
    environment:
      PORT: "5000"
      OTHERPEERS: "5001,5002"
  client2:
    image: disysexercise2
    expose:
    - "5000"
    - "5001"
    - "5002"
    environment:
      PORT: "5001"
      OTHERPEERS: "5000,5002"
  client3:
    image: disysexercise2
    expose:
    - "5000"
    - "5001"
    - "5002"
    environment:
      PORT: "5002"
      OTHERPEERS: "5000,5001"

